config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  resources :items do
    member do
      get 'category' # カテゴリー一覧表示
      get 'brand' # ブランド一覧表示
    end
  end

  resources :transactions, only: [:show] do
    member do
      post 'pay' #購入
      get 'done' #購入後
    end
  end
  resources :users, only: [:index, :show, :edit, :update] do
    collection do
      get 'logout'
    end
    member do
      get 'profile' # プロフィール
    end
  end
  resources :signup do
    collection do
      get 'selection' # 分岐
      get 'personal' # 会員情報を入力
      get 'phone' # 電話番号認証
      get 'address' # 住所入力
      get 'card' # 支払い方法
      get 'done' # 完了画面
      post 'pay', to: 'signup#pay'
    end
  end
  resources :cards, only: [:index, :new] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_action :save_to_session, only: :step2

  require "payjp"

  def personal
    # インスタンスの生成
    @user = User.new
    @user.build_user_detail # user_detailモデルと関連付ける

  end

  def phone

    # personalでの入力をsession保存
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password] 
    session[:password_confirmation] = user_params[:password_confirmation]
    # 以下はuser_detailsテーブルの情報
    session[:first_name] = user_detail_attributes_params[:first_name]
    session[:family_name] = user_detail_attributes_params[:family_name]
    session[:kana_first_name] =  user_detail_attributes_params[:kana_first_name]
    session[:kana_family_name] =  user_detail_attributes_params[:kana_family_name]
    session[:birthday] =  user_detail_attributes_params[:birthday]

    @user = User.new
    @user.build_user_detail # user_detailモデルと関連付ける

  end

  def address
    # phoneでの入力をsession保存
    session[:phone_number] = user_detail_attributes_params[:phone_number]

    @user = User.new
    @user.build_user_detail # user_detailモデルと関連付ける

  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト',
      card: params['payjp-token'],
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to done_signup_index_path
      else
        redirect_to pay_signup_index_path
      end
    end

  end

  def save_to_session
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password] 
    session[:password_confirmation] = user_params[:password_confirmation]

    # バリデーションをかけるため、仮でインスタンスに入力値を入れる
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    # インスタンスにバリデーションをかけ、通らなければ1step目のページを再度表示する
    unless @user.valid?
      render '/signup/step1'
    end

  end

  def create

    User.create(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    user = User.find_by(email: session[:email])
    UserDetail.create(
       user_id: user.id,
       first_name: session[:first_name],
       family_name: session[:family_name],
       kana_first_name: session[:kana_first_name],
       kana_family_name: session[:kana_family_name],
       birthday: session[:birthday],
       postalcode: user_detail_attributes_params[:postalcode],
      prefecture_id: user_detail_attributes_params[:prefecture_id],
      city: user_detail_attributes_params[:city],
      address: user_detail_attributes_params[:address],
      building: user_detail_attributes_params[:building],
      phone_number: user_detail_attributes_params[:phone_number])

    if User.create
      sign_in User.find_by(email: session[:email]) unless user_signed_in?
      redirect_to card_signup_index_path
    end
  end

  private

    def user_params
      params.require(:user).permit(
        :nickname, 
        :email, 
        :password, 
        :password_confirmation
      )
    end

    def user_detail_attributes_params
      params.require(:user).require(:user_detail_attributes).permit(
        :id,
        :first_name,
        :family_name,
        :kana_first_name,
        :kana_family_name,
        :birthday,
        :postalcode,
        :prefecture_id,
        :city,
        :address,
        :building,
        :phone_number
        )
    end

end

app/views/signup/address.html.haml
.single-container
  %header.regi-single-header
    %h1
      = link_to items_path do
        =image_tag "/assets/logo-gray.png", class: "regi-single-header__logo"
    %nav.progress-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li.active
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  .regi-main
    .regi-main__header
      %h2 住所入力
    .regi-main__form
      = form_for @user, url: signup_index_path, method: :post do |f|
        = f.fields_for :user_detail, @user.build_user_detail, url: signup_index_path, method: :post do |c|
          .form-group
            %label 郵便番号
            %span.required 必須
            %br
            = c.text_field :postalcode, class: "input-default", placeholder: '例) 123-4567', required: "true"
          .form-group
            %label 都道府県
            %span.required 必須
            %br
            = c.collection_select :prefecture_id, Prefecture.all, :id, :prefecture, {prompt: "--"}, {class: "prefecture-box"}
          .form-group
            %label 市区町村
            %span.required 必須
            %br
            = c.text_field :city, class: "input-default", placeholder: '例) 横浜市緑区', required: "true"
          .form-group
            %label 番地
            %span.required 必須
            %br
            = c.text_field :address, class: "input-default", placeholder: '例) 永田町1-1-1', required: "true"
          .form-group
            %label 建物名
            %span.elective 任意
            %br
            = c.text_field :building, class: "input-default", placeholder: '例) 桃山ビル18階'
          .form-group
            %label 電話
            %span.elective 任意
            %br
            = c.text_field :phone_number, class: "input-default", placeholder: '例) 0901234567'
          .form-group
            = f.submit "次へ進む", class: 'btn'
  = render 'layouts/login_footer'

app/views/signup/card.html.haml
.single-container
  %header.regi-single-header
    %h1
      = link_to items_path do
        =image_tag "/assets/logo-gray.png", class: "regi-single-header__logo"
    %nav.progress-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li.active
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  .regi-main
    .regi-main__header
      %h2 支払い方法
    .regi-main__form
      = form_tag(pay_signup_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
        .form-group
          %label カード番号
          %span.required 必須
          %br
          = text_field_tag "number", "", class: "input-default", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        .form-group
          %label 有効期限
          %span.required 必須
          %br
          %select.card-valid#exp_month{name: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span 月/
          %select.card-valid#exp_year{name: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %span 年
        .form-group
          %label セキュリティコード
          %span.required 必須
          %br
          = text_field_tag "cvc", "", class: "input-default", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        .form-group
          #card_token
          = submit_tag "登録する", id: "token_submit", class: 'btn'

= render 'layouts/login_footer'

app/views/signup/done.html.haml
.single-container
  %header.regi-single-header
    %h1
      = link_to items_path do
        =image_tag "/assets/logo-gray.png", class: "regi-single-header__logo"
    %nav.progress-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li.active
          完了
          .progress-status
  .regi-main
    .regi-main__header
      %h2 会員登録完了
    .regi-main__form
      .text-done
        %p
          ありがとうございます。
          %br
          会員登録が完了しました。
      .form-group
        = link_to "メルカリをはじめる", items_path, class: "btn"
= render 'layouts/login_footer'

app/views/signup/personal.html.haml
.single-container
  %header.regi-single-header
    %h1
      = link_to items_path do
        =image_tag "/assets/logo-gray.png", class: "regi-single-header__logo"
    %nav.progress-bar
      %ol.clearfix
        %li.active
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  .regi-main
    .regi-main__header
      %h2 会員情報入力
    .regi-main__form
      - if @user.errors.any?
        .regi-main__form__errors
          %h2= "#{@user.errors.full_messages.count}件のエラーが発生しました。"
          %ul
            - @user.errors.full_messages.each do |message|
              %li= message
      = form_for @user, url: phone_signup_index_path, method: :get do |f|
        = f.fields_for :user_detail, @user.build_user_detail, url: phone_signup_index_path, method: :get do |c|
          .form-group
            %label ニックネーム
            %span.required 必須
            %br
            = f.text_field :nickname, class: "input-default", placeholder: '例) メルカリ太郎', required: "true"
          .form-group
            %label メールアドレス
            %span.required 必須
            %br
            = f.email_field :email, class: "input-default", placeholder: 'PC・携帯どちらでも可', required: "true"
          .form-group
            %label パスワード
            %span.required 必須
            %br
            = f.password_field :password, class: "input-default", placeholder: '6文字以上', required: "true"
          .form-group
            %label パスワード（確認）
            %span.required 必須
            %br
            = f.password_field :password_confirmation, class: "input-default", placeholder: '6文字以上', required: "true"
          .form-group
            %h3 本人確認
            %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
          .form-group
            %label お名前（全角）
            %span.required 必須
            %br
            %li
              = c.text_field :first_name, class: "input-default input-half", placeholder: "例)山田", required: "true"
              = c.text_field :family_name, class: "input-default input-half", placeholder: "例)彩", required: "true"
          .form-group
            %label お名前カナ（全角）
            %span.required 必須
            %br
            %li
              = c.text_field :kana_first_name, class: "input-default input-half", placeholder: "例)ヤマダ", required: "true"
              = c.text_field :kana_family_name, class: "input-default input-half", placeholder: "例)アヤ", required: "true"

          .form-group
            %label 生年月日
            %span.required 必須
            %br
            .birthday-select-wrap
              = c.text_field :birthday, class: "input-default ", placeholder: "例)1990年1月1日 → 19900101と入力", required: "true"        
          .form-info-text
            %p ※本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .form-group
            = recaptcha_tags
            %p.text-center 
              「次へ進む」のボタンを押すことにより、
              = link_to "利用規約", "https://www.google.com/"
              に同意したものとみなします
          .form-group
            = f.submit "次へ進む", class: 'btn'
          .form-group
            %p.text-right
              = link_to "本人登録について＞", "https://www.google.com/"
= render 'layouts/login_footer'

app/views/signup/phone.html.haml
.single-container
  %header.regi-single-header
    %h1
      = link_to items_path do
        =image_tag "/assets/logo-gray.png", class: "regi-single-header__logo"
    %nav.progress-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li.active
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  .regi-main
    .regi-main__header
      %h2 電話番号の確認
    .regi-main__form
      = form_for @user, url: address_signup_index_path, method: :get do |f|
        = f.fields_for :user_detail, @user.build_user_detail, url: address_signup_index_path, method: :get do |c|
          .form-group
            %label 携帯電話の番号
            %br
            = c.telephone_field :phone_number, class: "input-default", placeholder: '携帯電話の番号を入力', required: "true"
            %p 本人確認のため、携帯電話のSMS（ショートメッセージサービス）を利用して認証を行います。

          .form-group
            = f.submit "SMSを送信する", class: 'btn'
            %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。            
          .form-group
            %p.text-right
              = link_to "電話番号の確認が必要な理由＞", "https://www.google.com/"
= render 'layouts/login_footer'

app/views/signup/selection.html.haml
.single-container
  %header.single-header
    %h1
      = link_to root_path do
        =image_tag "logo-gray.png", class: "single-header__logo"
  .single-main
    %section.signup-container
      %h2 新規会員登録
      .signup-inner
        .signup-content
          //メールアドレスでの登録
          %button.btn-default.btn-mail
            = link_to "メールアドレスで登録する", personal_signup_index_path
            %i.fa.fa-envelope
          //facebookでの登録
          %button.btn-default.btn-sns-facebook
            = link_to "facebookで登録する", user_facebook_omniauth_authorize_path 
            %i.fa.fa-facebook-square
          //Googleでの登録
          %button.btn-default.btn-sns-google
            = link_to "Googleで登録する", user_google_oauth2_omniauth_authorize_path
            %i.fa.fa-google
= render 'layouts/login_footer'


  

app/views/signup/step0.html.haml
.single-container
  %header.single-header
    %h1
      = link_to '/' do
        =image_tag "logo-gray.png", class: "single-header__logo"
  .single-main
    %section.signup-container
      %h2 新規会員登録
      .signup-inner
        .signup-content
          //メールアドレスでの登録
          %button.btn-default.btn-mail
            = link_to "メールアドレスで登録する", step1_signup_index_path
            %i.fa.fa-envelope
          //facebookでの登録
          %button.btn-default.btn-sns-facebook
            = link_to "facebookで登録する", ""
            %i.fa.fa-facebook-square
          //Googleでの登録
          %button.btn-default.btn-sns-google
            = link_to "Googleで登録する", ""
            %i.fa.fa-google
= render 'layouts/login_footer'


  

app/views/signup/step1.html.haml
.single-container
  %header.regi-single-header
    %h1
      = link_to '/' do
        =image_tag "/assets/logo-gray.png", class: "regi-single-header__logo"
    %nav.progress-bar
      %ol.clearfix
        %li.active
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  .regi-main
    .regi-main__header
      %h2 会員情報入力
    .regi-main__form
      - if @user.errors.any?
        .regi-main__form__errors
          %h2= "#{@user.errors.full_messages.count}件のエラーが発生しました。"
          %ul
            - @user.errors.full_messages.each do |message|
              %li= message
      = form_for @user, url: step2_signup_index_path, method: :get do |f|
        = f.fields_for :user_detail, @user.build_user_detail, url: step2_signup_index_path, method: :get do |c|
          .form-group
            %label ニックネーム
            %span.required 必須
            %br
            = f.text_field :nickname, class: "input-default", placeholder: '例) メルカリ太郎', required: "true"
          .form-group
            %label メールアドレス
            %span.required 必須
            %br
            = f.email_field :email, class: "input-default", placeholder: 'PC・携帯どちらでも可', required: "true"
          .form-group
            %label パスワード
            %span.required 必須
            %br
            = f.password_field :password, class: "input-default", placeholder: '8文字以上', required: "true"
          .form-group
            %label パスワード（確認）
            %span.required 必須
            %br
            = f.password_field :password_confirmation, class: "input-default", placeholder: '8文字以上', required: "true"
          .form-group
            %h3 本人確認
            %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
          .form-group
            %label お名前（全角）
            %span.required 必須
            %br
            %li
              = c.text_field :first_name, class: "input-default input-half", placeholder: "例)山田", required: "true"
              = c.text_field :family_name, class: "input-default input-half", placeholder: "例)彩", required: "true"
          .form-group
            %label お名前カナ（全角）
            %span.required 必須
            %br
            %li
              = c.text_field :kana_first_name, class: "input-default input-half", placeholder: "例)ヤマダ", required: "true"
              = c.text_field :kana_family_name, class: "input-default input-half", placeholder: "例)アヤ", required: "true"

          .form-group
            %label 生年月日
            %span.required 必須
            %br
            .birthday-select-wrap
              = c.text_field :birthday, class: "input-default ", placeholder: "例)1990年1月1日 → 19900101と入力", required: "true"        
          .form-info-text
            %p ※本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          //reCAPTCHA導入予定
          .form-group
            %img{:src => "/assets/recaptcha.png", class:"recaptcha-image"}/
            %p.text-center 
              「次へ進む」のボタンを押すことにより、
              = link_to "利用規約", "https://www.google.com/"
              に同意したものとみなします
          .form-group
            = f.submit "次へ進む", class: 'btn'
          .form-group
            %p.text-right
              = link_to "本人登録について＞", "https://www.google.com/"
= render 'layouts/login_footer'

app/views/signup/step2.html.haml
.single-container
  %header.regi-single-header
    %h1
      = link_to '/' do
        =image_tag "/assets/logo-gray.png", class: "regi-single-header__logo"
    %nav.progress-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li.active
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  .regi-main
    .regi-main__header
      %h2 電話番号の確認
    .regi-main__form
      = form_for @user, url: step3_signup_index_path, method: :get do |f|
        = f.fields_for :user_detail, @user.build_user_detail, url: step3_signup_index_path, method: :get do |c|
          .form-group
            %label 携帯電話の番号
            %br
            = c.telephone_field :phone_number, class: "input-default", placeholder: '携帯電話の番号を入力', required: "true"
            %p 本人確認のため、携帯電話のSMS（ショートメッセージサービス）を利用して認証を行います。

          .form-group
            = f.submit "SMSを送信する", class: 'btn'
            %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。            
          .form-group
            %p.text-right
              = link_to "電話番号の確認が必要な理由＞", "https://www.google.com/"
= render 'layouts/login_footer'

app/views/signup/step3.html.haml
.single-container
  %header.regi-single-header
    %h1
      = link_to '/' do
        =image_tag "/assets/logo-gray.png", class: "regi-single-header__logo"
    %nav.progress-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li.active
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  .regi-main
    .regi-main__header
      %h2 住所入力
    .regi-main__form
      = form_for @user, url: step4_signup_index_path, method: :get do |f|
        = f.fields_for :user_detail, @user.build_user_detail, url: step3_signup_index_path, method: :get do |c|
          .form-group
            %label 郵便番号
            %span.required 必須
            %br
            = c.text_field :postalcode, class: "input-default", placeholder: '例) 123-4567', required: "true"
          .form-group
            %label 都道府県
            %span.required 必須
            %br
            = c.collection_select :prefecture_id, Prefecture.all, :id, :prefecture, {prompt: "--"}, {class: "prefecture-box"}
          .form-group
            %label 市区町村
            %span.required 必須
            %br
            = c.text_field :city, class: "input-default", placeholder: '例) 横浜市緑区', required: "true"
          .form-group
            %label 番地
            %span.required 必須
            %br
            = c.text_field :address, class: "input-default", placeholder: '例) 永田町1-1-1', required: "true"
          .form-group
            %label 建物名
            %span.elective 任意
            %br
            = c.text_field :building, class: "input-default", placeholder: '例) 桃山ビル18階'
          .form-group
            %label 電話
            %span.elective 任意
            %br
            = c.text_field :phone_number, class: "input-default", placeholder: '例) 0901234567'
          .form-group
            = f.submit "次へ進む", class: 'btn'
  = render 'layouts/login_footer'

app/views/signup/step4.html.haml
.single-container
  %header.regi-single-header
    %h1
      = link_to '/' do
        =image_tag "/assets/logo-gray.png", class: "regi-single-header__logo"
    %nav.progress-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li.active
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  .regi-main
    .regi-main__header
      %h2 支払い方法
    .regi-main__form
      -# cardsテーブル未作成のため、仮で作成
      = form_for @user, url: signup_index_path, method: :post do |f|
        = f.fields_for :user_detail, @user.build_user_detail, url: signup_index_path, method: :post do |c|
          .form-group
            %label カード番号
            %span.required 必須
            %br
            -# cardsテーブル未作成のため、仮でuserで記入,required: "true"も解除
            = f.text_field :nickname, class: "input-default", placeholder: '半角数字のみ'
          .form-group
            %label 有効期限
            %span.required 必須
            %br
            %select.card-valid
              %option{value:"1"} 01
              %option{value:"2"} 02
              %option{value:"3"} 03
              %option{value:"4"} 04
              %option{value:"5"} 05
              %option{value:"6"} 06
              %option{value:"7"} 07
              %option{value:"8"} 08
              %option{value:"9"} 09
              %option{value:"10"} 10
              %option{value:"11"} 11
              %option{value:"12"} 12
            %span 月
            %br
            %select.card-valid
              %option{value:"19"} 19
              %option{value:"20"} 20
              %option{value:"21"} 21
              %option{value:"22"} 22
              %option{value:"23"} 23
              %option{value:"24"} 24
              %option{value:"25"} 25
              %option{value:"26"} 26
              %option{value:"27"} 27
              %option{value:"28"} 28
              %option{value:"29"} 29
            %span 年
          .form-group
            %label セキュリティコード
            %span.required 必須
            %br
            -# cardsテーブル未作成のため、仮でuserで記入
            = f.text_field :nickname, class: "input-default", placeholder: 'カード背面4桁もしくは3桁の番号'
            %p.text-right
              = link_to "カード裏面の番号とは？", "https://www.google.com/"
          .form-group
            = f.submit "次へ進む", class: 'btn'
= render 'layouts/login_footer'