config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  resources :items do
    member do
      get 'category' # カテゴリー一覧表示
      get 'brand' # ブランド一覧表示
    end
  end

  resources :transactions, only: [:show] do
    member do
      post 'pay' #購入
      get 'done' #購入後
    end
  end
  resources :users, only: [:index, :show, :edit, :update] do
    collection do
      get 'logout'
    end
    member do
      get 'profile' # プロフィール
    end
  end
  resources :signup do
    collection do
      get 'selection' # 分岐
      get 'personal' # 会員情報を入力
      get 'phone' # 電話番号認証
      get 'address' # 住所入力
      get 'card' # 支払い方法
      get 'done' # 完了画面
      post 'pay', to: 'signup#pay'
    end
  end
  resources :cards, only: [:index, :new] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  include AASM

  aasm :column => 'aasm_state' do
    # 状態の定義
    state :waiting, :initial => true #デフォルト値の指定
    state :wip, :done

    # waiting-出品中
    # wip-取引中
    # done-売却済

    # イベントの定義
    event :run do
      # 遷移の定義（出品中→取引中）
      transitions :from => :waiting, :to => :wip
    end

    event :finish do
      # 遷移の定義（取引中→売却済）
      transitions :from => :wip, :to => :done
    end

    event :wait do
      # 遷移の定義（キャンセル：→出品中への戻し）
      transitions :from => [:wip, :done], :to => :waiting
    end
  end
  
  has_many :item_images, dependent: :destroy
  belongs_to :user
  has_many :users, through: :users_items
  has_many :users, through: :likes
  belongs_to :category
  belongs_to :size
  belongs_to :status
  belongs_to :brand, optional: true
  belongs_to :delivery_fee_payer
  belongs_to :delivery_method
  belongs_to :prefecture
  belongs_to :shipping_day

  accepts_nested_attributes_for :item_images
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index # トップページ一覧表示
    # カテゴリー
    @items = Item.all.order('id DESC')
    @category1 = FirstCategory.find(1)
    @category2 = FirstCategory.find(2)
    @category3 = FirstCategory.find(3)
    @category4 = FirstCategory.find(7)
    
    # アイテムの制限
    @items1 = @items.where(category_id:1..122)
    @items2 = @items.where(category_id:123..228)
    @items3 = @items.where(category_id:229..341)
    @items4 = @items.where(category_id:604..689)

    #ブランド
    @brand1 = Brand.find(49)
    @brand2 = Brand.find(50)
    @brand3 = Brand.find(52)
    @brand4 = Brand.find(51)
  end

  def category # カテゴリー一覧表示
    items = Item.all
    @first_items = []
    @second_items = []
    @third_items = []
    items.each do |item|
      if (params[:id].to_i) < 13
        if item.category.first_category_id == (params[:id].to_i)
          @first_items << item
        end
      elsif (params[:id].to_i) < 145
        if item.category.second_category_id == (params[:id].to_i)
          @second_items << item
        end
      else
        if item.category.third_category_id == (params[:id].to_i)
          @third_items << item
        end
      end
    end
  end

  def brand # ブランド一覧表示
    @brand_items = Item.all.where(brand_id: params[:id]).order('id DESC')
  end

  def new # 商品出品
    @item = Item.new
    @item.item_images.build
  end

  def create # 商品出品完了
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to root_path
    end
  end

  def show # 商品詳細表示
    @item = Item.find(params[:id])
    @allitems = Item.all.order('id DESC')
    @images = ItemImage.all
  end

  def edit # 商品情報編集
  end

  def update # 商品情報編集完了
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy if item.user_id == current_user.id
  end

  private

  def item_params
    params.require(:item).permit(:category_id, :item_title, :description, :status_id, :price, :brand_id, :delivery_fee_payer_id, :prefecture_id, :shipping_day_id, :size_id, :delivery_method_id, :category, item_images_attributes: [:image_url, :item_id])
  end

end

app/views/items/brand.html.haml
= render 'layouts/header'
= render 'layouts/pankuzu'

.brand__single-column
  .content
    %section
      %h1
        - if @brand_items.present?
          = "#{@brand_items[0].brand[:brand]}の商品一覧"
        - else
          該当の商品がありません
      .contents__items
        - @brand_items.each do |item|
          = link_to item_path(item.id), class: 'contents__items-frame' do
            = image_tag(item.item_images[0].image_url, width: '135', alt: '商品画像')
            - if item.aasm_state == 'done'
              %p.contents__items-frame-sold
            .contents__items__detail
              %p.title
                = item.item_title
              %span.price 
                ¥
                = item.price
              %span.likes
                100

.main__foot-visual 
.sellbutton
  = link_to new_item_path do
    %p 出品
    =fa_icon "camera"
= render 'layouts/footer'

app/views/items/category.html.haml
= render 'layouts/header'
= render 'layouts/pankuzu'
.category__single-column
  .content
    %section
      %h1
        - if @first_items.present?
          = "#{@first_items[0].category.first_category[:first_category]}の商品一覧"
        - elsif @second_items.present?
          = "#{@second_items[0].category.second_category[:second_category]}の商品一覧"
        - elsif @third_items.present?
          = "#{@third_items[0].category.third_category[:third_category]}の商品一覧"
        - else
          該当の商品がありません
      .contents__items
        - if @first_items.present?
          - @first_items.reverse!.each do |item|
            = link_to item_path(item.id), class: 'contents__items-frame' do
              = image_tag(item.item_images[0].image_url, width: '135', alt: '商品画像')
              - if item.aasm_state == 'done'
                %p.contents__items-frame-sold
              .contents__items__detail
                %p.title
                  = item.item_title
                %span.price 
                  ¥
                  = item.price
                %span.likes
                  100
        - elsif @second_items.present?
          - @second_items.reverse!.each do |item|
            = link_to item_path(item.id), class: 'contents__items-frame' do
              = image_tag(item.item_images[0].image_url, width: '135', alt: '商品画像')
              - if item.aasm_state == 'done'
                %p.contents__items-frame-sold
              .contents__items__detail
                %p.title
                  = item.item_title
                %span.price 
                  ¥
                  = item.price
                %span.likes
                  100
        - elsif @third_items.present?
          - @third_items.reverse!.each do |item|
            = link_to item_path(item.id), class: 'contents__items-frame' do
              = image_tag(item.item_images[0].image_url, width: '135', alt: '商品画像')
              - if item.aasm_state == 'done'
                %p.contents__items-frame-sold
              .contents__items__detail
                %p.title
                  = item.item_title
                %span.price 
                  ¥
                  = item.price
                %span.likes
                  100
        - else

.main__foot-visual 
.sellbutton
  = link_to new_item_path do
    %p 出品
    =fa_icon "camera"
= render 'layouts/footer'

app/views/items/destroy.html.haml
.contents.row
  .success
    %h3
      削除が完了しました。
    %a.btn{:href => "/"} トップページへ戻る

app/views/items/index.html.haml
= render 'layouts/header'
.main__visual
.main__single-column
  .content
    %section
      %h1 ピックアップカテゴリー
      %h2
        = link_to "#{@category1.first_category}新着アイテム", category_item_path(1)
      .contents__items
        - @items1.first(4).each do |item|
          = link_to item_path(item.id), class: 'contents__items-frame' do
            = image_tag(item.item_images[0].image_url, alt: '商品画像')
            - if item.aasm_state == 'done'
              %p.contents__items-frame-sold
            .contents__items__detail
              %p.title
                = item.item_title
              %span.price 
                ¥
                = item.price
              %span.likes
                100
      .contents__all-items
        = link_to 'すべての商品を見る', category_item_path(1)

      %h2
        = link_to "#{@category2.first_category}新着アイテム", category_item_path(2)
      .contents__items
        - @items2.first(4).each do |item|
          = link_to item_path(item.id), class: 'contents__items-frame' do
            = image_tag(item.item_images[0].image_url, width: '135', alt: '商品画像')
            - if item.aasm_state == 'done'
              %p.contents__items-frame-sold
            .contents__items__detail
              %p.title
                = item.item_title
              %span.price 
                ¥
                = item.price
              %span.likes
                =fa_icon "heart-o"
                135
      .contents__all-items
        = link_to 'すべての商品を見る', category_item_path(2)

      %h2
        = link_to "#{@category3.first_category}新着アイテム", category_item_path(3)
      .contents__items
        - @items3.first(4).each do |item|
          = link_to item_path(item.id), class: 'contents__items-frame' do
            = image_tag(item.item_images[0].image_url, width: '135', alt: '商品画像')
            - if item.aasm_state == 'done'
              %p.contents__items-frame-sold
            .contents__items__detail
              %p.title
                = item.item_title
              %span.price 
                ¥
                = item.price
              %span.likes
                =fa_icon "heart-o"
                135
      .contents__all-items
        = link_to 'すべての商品を見る', category_item_path(3)

      %h2
        = link_to "#{@category4.first_category}新着アイテム", category_item_path(7)
      .contents__items
        - @items4.first(4).each do |item|
          = link_to item_path(item.id), class: 'contents__items-frame' do
            = image_tag(item.item_images[0].image_url, width: '135', alt: '商品画像')
            - if item.aasm_state == 'done'
              %p.contents__items-frame-sold
            .contents__items__detail
              %p.title
                = item.item_title
              %span.price 
                ¥
                = item.price
              %span.likes
                =fa_icon "heart-o"
                135
      .contents__all-items
        = link_to 'すべての商品を見る', category_item_path(7)

    %section
      %h1.pickupbrand ピックアップブランド
      %h2
        = link_to brand_item_path(49), alt: 'シャネル' do
          = "#{@brand1.brand} 新着アイテム"
      .contents__items
        -@items.where(brand_id: 49).order('id DESC').first(4).each do |item|
          = link_to item_path(item.id), class: 'contents__items-frame' do
            - item.item_images.first(1).each do |image|
              = image_tag(image.image_url, alt: '商品画像')
              - if item.aasm_state == 'done'
                %p.contents__items-frame-sold
              .contents__items__detail
                %p.title
                  = item.item_title
                %span.price 
                  ¥
                  = item.price
                %span.likes
                  =fa_icon "heart-o"
                  135
      .contents__all-items
        = link_to 'すべての商品をみる', brand_item_path(49)

      %h2
        = link_to brand_item_path(50), alt: 'ルイヴィトン' do
          = "#{@brand2.brand} 新着アイテム"
      .contents__items
        -@items.where(brand_id: 50).order('id DESC').first(4).each do |item|
          = link_to item_path(item.id), class: 'contents__items-frame' do
            - item.item_images.first(1).each do |image|
              = image_tag(image.image_url, alt: '商品画像')
              - if item.aasm_state == 'done'
                %p.contents__items-frame-sold
              .contents__items__detail
                %p.title
                  = item.item_title
                %span.price 
                  ¥
                  = item.price
                %span.likes
                  =fa_icon "heart-o"
                  135
      .contents__all-items
        = link_to 'すべての商品をみる', brand_item_path(50)

      %h2
        = link_to brand_item_path(52), alt: 'シュプリーム' do
          = "#{@brand3.brand} 新着アイテム"
      .contents__items
        -@items.where(brand_id: 52).order('id DESC').first(4).each do |item|
          = link_to item_path(item.id), class: 'contents__items-frame' do
            - item.item_images.first(1).each do |image|
              = image_tag(image.image_url, alt: '商品画像')
              - if item.aasm_state == 'done'
                %p.contents__items-frame-sold
              .contents__items__detail
                %p.title
                  = item.item_title
                %span.price 
                  ¥
                  = item.price
                %span.likes
                  =fa_icon "heart-o"
                  135
      .contents__all-items
        = link_to 'すべての商品をみる', brand_item_path(52)
        
      %h2
        = link_to brand_item_path(51), alt: 'ナイキ' do
          = "#{@brand4.brand} 新着アイテム"
      .contents__items
        -@items.where(brand_id: 51).order('id DESC').first(4).each do |item|
          = link_to item_path(item.id), class: 'contents__items-frame' do
            - item.item_images.first(1).each do |image|
              = image_tag(image.image_url, alt: '商品画像')
              - if item.aasm_state == 'done'
                %p.contents__items-frame-sold
              .contents__items__detail
                %p.title
                  = item.item_title
                %span.price 
                  ¥
                  = item.price
                %span.likes
                  =fa_icon "heart-o"
                  135
      .contents__all-items
        = link_to 'すべての商品をみる', brand_item_path(51)

.main__foot-visual 
.sellbutton
  = link_to new_item_path do
    %p 出品
    =fa_icon "camera"
= render 'layouts/footer'

app/views/items/new.html.haml
.single-container
  .single-header
    =link_to root_path do
      =image_tag("mercari.jpg")
  .single-main
    .sell-container
      .sell-container__inner
        = form_for(@item) do |f|
          = f.fields_for :item_images do |c|
            .sell-container__inner__head
              %h2
                商品の情報を入力
            .sell-upload-box
              = f.label :image, "出品画像", {class: 'form-label'}
              %span.form-require
                必須
              %p
                最大10枚までアップロードできます。
              .sell-dropbox-container
                %label.image-uploader
                  = c.file_field :image_url
                  .sell-upload-drop-box
                    %p ドラッグアンドドロップ</br>またはクリックしてファイルをアップロード
          .sell-content
            .sell-content--1
              .form-group
                .form-label
                  商品名
                  %span.form-require
                    必須
                %div
                  %input{name: 'item[item_title]', class: 'item-name', placeholder: '商品名（必須40文字まで）'}
              .form-group
                .form-label
                  商品の説明
                  %span.form-require
                    必須
                %textarea{name: "item[description]", class: "item-description", placeholder: "商品の説明（必須1000文字以内）"}

          .sell-content.clearfix
            .sell-content--2
              %h3.sell-sub-head
                商品の詳細
              .sell-form-box
                .form-group
                  = f.label :state, 'カテゴリー', {class: 'form-label'}
                  %span.form-require
                    必須
                  %div
                    .select-wrap
                      %i.icon-arrow-button
                      %select{name: "item[category_id]", class: 'select-default'}
                        %option{:value => "0"}  ---
                        %option{:value => "1"}  レディース
                        %option{:value => "2"}  メンズ
                        %option{:value => "3"}  ベビー・キッズ
                        %option{:value => "4"}  インテリア・住まい・小物
                        %option{:value => "5"}  本・音楽・ゲーム
                        %option{:value => "6"}  おもちゃ・ホビー・グッズ
                        %option{:value => "7"}  コスメ・香水・美容
                        %option{:value => "8"}  家電・スマホ・カメラ
                        %option{:value => "9"}  スポーツ・レジャー
                        %option{:value => "10"}  ハンドメイド
                        %option{:value => "11"}  チケット
                        %option{:value => "12"}  自動車・オートバイ
                        %option{:value => "13"}  その他
                .form-group
                  = f.label :state, 'サイズ', {class: 'form-label'}
                  %span.form-require
                    必須
                  %div
                    .select-wrap
                      %i.icon-arrow-button
                      %select{name: "item[size_id]", class: 'select-default'}
                        %option{:value => "0"}  ---
                        %option{:value => "1"}  S
                        %option{:value => "2"}  M
                        %option{:value => "3"}  L
                        %option{:value => "4"}  25
                        %option{:value => "5"}  26
                        %option{:value => "6"}  27
                .form-group
                  = f.label :state, 'ブランド', {class: 'form-label'}
                  %span.form-require
                    必須
                  %div
                    .select-wrap
                      %i.icon-arrow-button
                      %select{name: "item[brand_id]", class: 'select-default'}
                        %option{:value => "0"}  ---
                        %option{:value => "1"}  A
                        %option{:value => "2"}  B
                        %option{:value => "3"}  C
                        %option{:value => "4"}  D
                        %option{:value => "5"}  E
                        %option{:value => "6"}  F
                .form-group
                  = f.label :state, '商品の状態', {class: 'form-label'}
                  %span.form-require
                    必須
                  %div
                    .select-wrap
                      %i.icon-arrow-button
                      %select{name: 'item[status_id]', class: 'select-default'}
                        %option{:value => "0"}  ---
                        %option{:value => "1"}  新品、未使用
                        %option{:value => "2"}  未使用に近い
                        %option{:value => "3"}  目立った傷や汚れなし
                        %option{:value => "4"}  やや傷や汚れあり
                        %option{:value => "3"}  傷や汚れあり
                        %option{:value => "4"}  全体的に状態が悪い

          .sell-content.clearfix
            .sell-content--3
              %h3.sell-sub-head
                配送について
              = link_to '#', class: 'form-question' do
                ?
              .sell-form-box
                .form-group
                  = f.label :release, "配送料の負担", {class: 'form-label'}
                  %span.form-require
                    必須
                  %div
                    .select-wrap
                      %i.icon-arow-button
                      %select{name: 'item[delivery_fee_payer_id]', class: 'select-default'}
                        %option{:value => "0"}  ---
                        %option{:value => "1"}  送料込み（出品者負担）
                        %option{:value => "2"}  着払い（購入者負担）
                .form-group
                  = f.label :release, "発送元の地域", {class: 'form-label'}
                  %span.form-require
                    必須
                  %div
                    .select-wrap
                      %i.icon-arow-button
                      = f.collection_select :prefecture_id, Prefecture.all, :id, :prefecture, {prompt: "---"}, {class: "select-default"}
                .form-group
                  = f.label :release, "発送までの日数", {class: 'form-label'}
                  %span.form-require
                    必須
                  %div
                    .select-wrap
                      %i.icon-arow-button
                      %select{name: 'item[shipping_day_id]', class: 'select-default'}
                        %option{:value => "0"}  --
                        %option{:value => "1"}  1~2日で発送
                        %option{:value => "2"}  2~3日で発送
                        %option{:value => "3"}  4~7日で発送
                .form-group
                  = f.label :release, "発送方法", {class: 'form-label'}
                  %span.form-require
                    必須
                  %div
                    .select-wrap
                      %i.icon-arow-button
                      %select{name: 'item[delivery_method_id]', class: 'select-default'}
                        %option{:value => "0"}  --
                        %option{:value => "1"}  ゆうパック
                        %option{:value => "2"}  らくらくメルカリ便
                        %option{:value => "3"}  手渡し

          .sell-content
            .sell-content--4
              %h3.sell-sub-head
                販売価格(300〜9,999,999)
              = link_to '#', class: 'form-question' do
                ?
              .sell-form-box
                %ul.sell-price
                  %li.form-group
                    .l-left
                      = f.label :price, '価格'
                      %span.form-require
                        必須
                    .l-right.sell-price-input
                      %input{name: 'item[price]',class: 'input-default-second', placeholder: "例）300"}

              .commision
                .l-left
                  販売手数料 (10%)
                .l-right
                  ー
              .profits
                .l-left
                  販売利益
                .l-right
                  ー
          .sell-content
            .sell-content--5
              %p
                禁止されている出品、行為を必ずご確認ください。</br>
                またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
              .form-group
                = f.submit "出品する", class: "btn btn__red"
                = link_to "もどる", root_path, class: "btn btn__gray"

%footer.single-footer
  %nav
    %ul.clearfix
      %li
        = link_to '' do
          プライバシーポリシー
      %li
        = link_to '' do
          利用規約
      %li
        = link_to '' do
          特定商取引に関する表記
  = link_to '', class: 'single-footer-logo' do
    =image_tag('logo-gray.jpg', width: '80')
  %p
    %small
      © 2019 Mercari

app/views/items/show.html.haml
= render "layouts/header"
.item-detail
  .l-container
    .l-content
      .l-content__container
        %h2.item-detail-name
          = @item.item_title
        .item-content
          .item-content__main-photo
            = image_tag(@item.item_images[0].image_url, width: '135', alt: '商品画像')
            - if @item.aasm_state == 'done'
              .item-content__main-photo-sold
          - @item.item_images.each_with_index do |image, i|
            - if i > 0 and i < 4
              .item-content__sub-photo
                =image_tag(image.image_url, alt: '商品画像')
        %table.item-detail-table
          %tbody
            %tr
              %th
                出品者
              %td
                = link_to "", class: 'item-detail-table__link' do
                  = @item.user.nickname
                .item-user-rating
                  =fa_icon "smile-o"
                  38
                  =fa_icon "meh-o"
                  11
                  =fa_icon "frown-o"
                  3
            %tr
              %th
                カテゴリー
              %td
                = link_to @item.category.first_category[:first_category], category_item_path(@item.category.first_category_id), class: 'item-detail-table__link'
                %br
                = link_to @item.category.second_category[:second_category], category_item_path(@item.category.second_category_id), class: 'item-detail-table__link'
                %br
                = link_to @item.category.third_category[:third_category], category_item_path(@item.category.third_category_id), class: 'item-detail-table__link'
            %tr
              %th
                ブランド
              %td
                - unless @item.brand.nil?
                  = link_to @item.brand.brand, brand_item_path(@item.brand_id), class: 'item-detail-table__link'
            %tr
              %th
                商品の状態
              %td
                = @item.status.status
            %tr
              %th
                配送料の負担
              %td
                = @item.delivery_fee_payer.delivery_fee_payer
            %tr
              %th
                配送の方法
              %td
                = @item.delivery_method.delivery_method
            %tr
              %th
                配送元地域
              %td
                = link_to @item.prefecture.prefecture, "", class: 'item-detail-table__link'
            %tr
              %th
                配送の目安
              %td
                = @item.shipping_day.shipping_day
      .item-detail-price
        %span.item-detail-price__bold
          = number_to_currency(@item.price, unit: "￥", precision: 0)
        %span.item-detail-price__tax
          （税込）
        %span.item-detail-price__shipping-fee
          = "#{@item.delivery_fee_payer.delivery_fee_payer}".sub(/\(.*/, '')
      .item-btn
        - if @item.user_id == current_user.id
          .item-btn__destroy__gray
            = link_to 'この商品を削除する', "/items/#{@item.id}", method: :delete
        - else
          - if @item.aasm_state == 'done'
            .item-btn__buy__gray
              売り切れました
          -else
            .item-btn__buy__red
              = link_to '購入画面に進む', transaction_path(params[:id]), method: :get
      .item-description
        %p
          = @item.description
      .item-button-container
        .item-button-left
          %button.item-button.item-button-like
            %span.likes
              =fa_icon "heart-o"
            %span
              いいね!
          %button.item-button.item-button-report.clearfix
            %span.report
              =fa_icon 'flag'
            %span
              不適切な商品の報告
        .item-button-right
          %span.icon-lock
            =fa_icon 'lock-alt'
          %span
            あんしん・あんぜんへの取り組み

.item-detail
  .l-container
    .comment-box
      .comment-contents
        =image_tag("icon.jpg", class: "user-image")
        .user-name
          %p
            太郎
        .comment
          どのくらい使用したものでしょうか？
          .comment-date
            ４日前
      .comment-contents
        =image_tag("icon.jpg", class: "user-image")
        .user-name
          %p
          二郎
        .comment
          サイズは何号でしょうか？
          .comment-date
            ３日前
      .comment-contents
        =image_tag("icon.jpg", class: "user-image")
        .user-name
          %p
            三郎
        .comment
          素材は革ですか？ゴムですか？
          .comment-date
            ２日前
    .precautionary-note
      %p
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。    
    %textarea{name: "url"}

    .selling-state
      %h3
        売り切れのためコメントできません

%ul.nav-item-link-prev-next
  %li.nav-item-link-prev
    = link_to '< 前の商品', '' 
  %li.nav-item-link-next
    = link_to '次の商品 >', ''

.item-detail
  .social-media-box
    .icon-box
      %i.fa.fa-facebook
    .icon-box
      %i.fa.fa-twitter
    .icon-box
      %i.fa.fa-line
    .icon-box
      %i.fa.fa-pinterest

.other-items
  .other-item
    %h2
      = "#{@item.user.nickname}さんのその他の出品"
.items-box-content
  %section
    .contents__items 
      - @allitems.where(user_id: @item.user).each_with_index do |item, i|
        - if 0 <= i and i <= 2
          = link_to item_path(item.id), class: 'contents__items-frame' do
            = image_tag(item.item_images[0].image_url, alt: '商品画像')
            - if item.aasm_state == 'done'
              %p.contents__items-frame-sold
            .contents__items__detail
              %p.title
                = item.item_title
              %span.price
                = number_to_currency(item.price, unit: "￥", precision: 0)
              %span.likes
                =fa_icon "heart-o"
                12
    .contents__items 
      - @allitems.where(user_id: @item.user).each_with_index do |item, i|
        - if 3 <= i and i <= 5
          = link_to item_path(item.id), class: 'contents__items-frame' do
            = image_tag(item.item_images[0].image_url, alt: '商品画像')
            - if item.aasm_state == 'done'
              %p.contents__items-frame-sold
            .contents__items__detail
              %p.title
                = item.item_title
              %span.price
                = number_to_currency(item.price, unit: "￥", precision: 0)
              %span.likes
                =fa_icon "heart-o"
                12

.other-items
  .other-item
    %h2
      - if @item.brand.nil?
        = "#{@item.category.third_category[:third_category]} その他の商品"
      - else
        = "#{@item.brand.brand}の#{@item.category.third_category[:third_category]} その他の商品"
.items-box-content
  %section
    .contents__items 
      - if @item.brand.nil?
        - @allitems.where(category_id: @item.category_id).each_with_index do |item, i|
          - if 0 <= i and i <= 2
            = link_to item_path(item.id), class: 'contents__items-frame' do
              = image_tag(item.item_images[0].image_url, alt: '商品画像')
              - if item.aasm_state == 'done'
                %p.contents__items-frame-sold
              .contents__items__detail
                %p.title
                  = item.item_title
                %span.price
                  = number_to_currency(item.price, unit: "￥", precision: 0)
                %span.likes
                  =fa_icon "heart-o"
                  12
      - else
        - @allitems.where(brand_id: @item.brand_id).where(category_id: @item.category_id).each_with_index do |item, i|
          - if 1 <= i and i <= 3
            = link_to item_path(item.id), class: 'contents__items-frame' do
              = image_tag(item.item_images[0].image_url, alt: '商品画像')
              - if item.aasm_state == 'done'
                %p.contents__items-frame-sold
              .contents__items__detail
                %p.title
                  = item.item_title
                %span.price
                  = number_to_currency(item.price, unit: "￥", precision: 0)
                %span.likes
                  =fa_icon "heart-o"
                  12
.main-visual

= render "layouts/footer"