config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  resources :items do
    member do
      get 'category' # カテゴリー一覧表示
      get 'brand' # ブランド一覧表示
    end
  end

  resources :transactions, only: [:show] do
    member do
      post 'pay' #購入
      get 'done' #購入後
    end
  end
  resources :users, only: [:index, :show, :edit, :update] do
    collection do
      get 'logout'
    end
    member do
      get 'profile' # プロフィール
    end
  end
  resources :signup do
    collection do
      get 'selection' # 分岐
      get 'personal' # 会員情報を入力
      get 'phone' # 電話番号認証
      get 'address' # 住所入力
      get 'card' # 支払い方法
      get 'done' # 完了画面
      post 'pay', to: 'signup#pay'
    end
  end
  resources :cards, only: [:index, :new] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"

  def index
    @card = Card.where(user_id: current_user.id).first

    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @card_brand = @default_card_information.brand      
      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "MasterCard"
        @card_src = "master-card.svg"
      when "American Express"
        @card_src = "american_express.svg"
      when "Saison Card"
        @card_src = "saison-card.svg"
      when "Diners Club"
        @card_src = "dinersclub.svg"
      when "Discover"
        @card_src = "discover.svg"
      end
    end
  end

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "index" if card.exists?
  end

  def pay 
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト',
      card: params['payjp-token']
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "index"
  end

end

app/views/cards/index.html.haml
= render 'layouts/header'
= render 'layouts/pankuzu'
.main__double-column
  = render 'layouts/sidebar'

  .contents--card
    %p.contents--card-title 支払い方法
    .contents--card__inner
      .contents--card__lists
        %p.contents--card__lists-title クレジットカード一覧
        - if @card.present?
          .contents--card__details
            .contents--card__details-left
              = image_tag "credit-cards/#{@card_src}", width: '30', height: '24', alt: @card_brand, id: "card_image"
              %p
                = "**** **** **** " + @default_card_information.last4
              %p
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = format('%02d', exp_month) + " / " + exp_year
              %input{type: "hidden", name: "card_id", value: ""}
            .contents--card__details-right
              = form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
                %input{ type: "hidden", name: "card_id", value: "" }
                %button 削除する
        - else
          .contents--card__add
            = link_to "クレジットカードを追加する", new_card_path
      %p.contents--card__inner__payment
        = link_to "支払い方法について", ""

.sellbutton
  = link_to new_item_path do
    %p 出品
    =fa_icon "camera"
= render 'layouts/footer'

app/views/cards/new.html.haml
= render 'layouts/header'
= render 'layouts/pankuzu'
.main__double-column
  = render 'layouts/sidebar'

  .regi-main
    .regi-main-cardsnew__header
      %h2 クレジットカード情報入力
    .regi-main__form
      = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
        .form-group
          %label カード番号
          %span.required 必須
          %br
          = text_field_tag "number", "", class: "input-default", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          .form-group-cardsnewimage
            = image_tag "credit-cards/visa.svg", width: '52', height: '20'
            = image_tag "credit-cards/master-card.svg", width: '28', height: '20'
            = image_tag "credit-cards/saison-card.svg", width: '30', height: '20'
            = image_tag "credit-cards/jcb.svg", width: '28', height: '20'
            = image_tag "credit-cards/american_express.svg", width: '28', height: '20'
            = image_tag "credit-cards/dinersclub.svg", width: '28', height: '20'
            = image_tag "credit-cards/discover.svg", width: '28', height: '20'
        .form-group
          %label 有効期限
          %span.required 必須
          %br
          %select.card-valid#exp_month{name: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span 月/
          %select.card-valid#exp_year{name: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %span 年
        .form-group
          %label セキュリティコード
          %span.required 必須
          %br
          = text_field_tag "cvc", "", class: "input-default", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
        .form-group
          #card_token
          = submit_tag "追加する", id: "token_submit", class: 'btn'
.sellbutton
  = link_to new_item_path do
    %p 出品
    =fa_icon "camera"
= render 'layouts/footer'

app/views/cards/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button 削除する