config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  resources :items do
    member do
      get 'category' # カテゴリー一覧表示
      get 'brand' # ブランド一覧表示
    end
  end

  resources :transactions, only: [:show] do
    member do
      post 'pay' #購入
      get 'done' #購入後
    end
  end
  resources :users, only: [:index, :show, :edit, :update] do
    collection do
      get 'logout'
    end
    member do
      get 'profile' # プロフィール
    end
  end
  resources :signup do
    collection do
      get 'selection' # 分岐
      get 'personal' # 会員情報を入力
      get 'phone' # 電話番号認証
      get 'address' # 住所入力
      get 'card' # 支払い方法
      get 'done' # 完了画面
      post 'pay', to: 'signup#pay'
    end
  end
  resources :cards, only: [:index, :new] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/views/layouts/_footer.html.haml
%footer

app/views/layouts/_login_footer.html.haml
%footer.single-footer
  %nav
    %ul.single-footer__menu
      %li
        = link_to '', class: 'single-footer__menu__content' do
          プライバシーポリシー
      %li
        = link_to '', class: 'single-footer__menu__content' do
          メルカリ利用規約
      %li
        = link_to '', class: 'single-footer__menu__content' do
          特定商取引に関する表記

    = link_to class: 'single-footer-image' do
      =image_tag "image-gray.png", class: "footer-image"

  %p.footer-text
    %small © 2019 Mercari

app/views/layouts/_pankuzu.html.haml
.pankuzu
  .pankuzu-inner
    %p
      = link_to "メルカリ", root_path
      - if  @brand_items.present?
        = @brand_items[0].brand[:brand]
      - elsif @user.present?
        マイページ
      - elsif @first_items.present?
        = "#{@first_items[0].category.first_category[:first_category]}"
      - elsif @second_items.present?
        = link_to "#{@second_items[0].category.first_category[:first_category]}", category_item_path(@second_items[0].category.first_category[:id])
        = "#{@second_items[0].category.second_category[:second_category]}"
      - elsif @third_items.present?
        = link_to "#{@third_items[0].category.first_category[:first_category]}", category_item_path(@third_items[0].category.first_category[:id])
        = link_to "#{@third_items[0].category.second_category[:second_category]}", category_item_path(@third_items[0].category.second_category[:id])
        = "#{@third_items[0].category.third_category[:third_category]}"

app/views/layouts/_sidebar.html.haml
.sidebar
  %nav
    %ul
      %li
        = link_to "マイページ", user_path(current_user)
      %li
        = link_to "お知らせ", ""
      %li
        = link_to "やることリスト", ""
      %li
        = link_to "いいね！一覧", ""
      %li
        = link_to "出品する", new_item_path
      %li
        = link_to "出品した商品 - 出品中", ""
      %li
        = link_to "出品した商品 - 取引中", ""
      %li
        = link_to "出品した商品 - 売却済み", ""
      %li
        = link_to "購入した商品 - 取引中", ""
      %li
        = link_to "購入した商品 - 過去の取引", ""
      %li
        = link_to "ニュース一覧", ""
      %li
        = link_to "評価一覧", ""
      %li
        = link_to "ガイド", ""
      %li
        = link_to "お問い合わせ", ""
    %p メルペイ
    %ul
      %li
        = link_to "売上・振込申請", ""
      %li
        = link_to "ポイント", ""
    %p 設定
    %ul
      %li
        = link_to "プロフィール", profile_user_path(current_user)
      %li
        = link_to "発送元・お届け先住所変更", ""
      %li
        = link_to "支払い方法", cards_path
      %li
        = link_to "メール/パスワード", ""
      %li
        = link_to "本人情報", edit_user_path(current_user)
      %li
        = link_to "電話番号の確認", ""
      %li
        = link_to "ログアウト", logout_users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}
    %title FreemarketSample0622a
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield